### PR TITLE
Move main.go to dagger_cue_lsp package

### PR DESCRIPTION
**Pull request by marcosnils**
Also added README instructions on how to install using `go install`

- dagger deps are bumped to latest as well

Signed-off-by: Marcos Lilljedahl <marcosnils@gmail.com>

### CODE REVIEW

**Comment by marcosnils** [comment]
fixing CI

**Comment by marcosnils** [comment]
Done. I'd guess this requires some changes on how the engine is importing the LSP, correct?

**Comment by dolanor** [comment]
> Done. I'd guess this requires some changes on how the engine is importing the LSP, correct?

No, that's what I was saying about the nice design in the sync.
The dagger binary imports `./server` as is the dagger LSP main. And that's it.

**Comment by marcosnils** [comment]
Nice!

sent from mobile

Em qui, 21 de jul de 2022 18:10, Tanguy ⧓ Herrmann ***@***.***>
escreveu:

**Comment by TomChv** [comment]
I'll solve conflict and merge your PR :D

**Pull request merged**
